version: '3'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "xp123!@#"
    ports:
      - "1433:1433"
    volumes:
      - D:\Projetos\volumes\sqlserver:/var/opt/mssql/data